### PR TITLE
devDeps: webpack@2->3

### PR DESCRIPTION
**Pull request by legobeat**

### CODE REVIEW

**Review by Mrtenz — COMMENTED** [review]
Why bump to v3 instead of v5 for example?

**Comment by legobeat** [comment]
> Why bump to v3 instead of v5 for example?


webpack5 has further breaking changes and can come later.

**Review by mcmire — APPROVED** [review]
Looks good.

**Comment by legobeat** [comment]
@SocketSecurity ignore os-browserify@0.3.0
    @SocketSecurity ignore hasown@2.0.0
    @SocketSecurity ignore estraverse@4.3.0
    @SocketSecurity ignore async@2.6.4
    @SocketSecurity ignore async@0.1.9
    @SocketSecurity ignore escope@3.6.0
    @SocketSecurity ignore ms@2.1.2
    @SocketSecurity ignore browserify-zlib@0.2.0
    @SocketSecurity ignore combined-stream@0.0.3
    @SocketSecurity ignore form-data@0.0.3
    @SocketSecurity ignore mime@1.2.2

authorship ok

**Comment by legobeat** [comment]
@SocketSecurity ignore setimmediate@1.0.5

no readme ok

**Pull request merged**
